### ISSUE TITLE
Login with OKTA SAML2 SP does not work

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#65]
We get the following exception with the OKTA XML:

```
Internal Server Error: /saml/sso/okta/
Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./saml/views.py", line 77, in sso
    auth = init_saml_auth(req, idp_shortname=idp_shortname)
  File "./saml/views.py", line 49, in init_saml_auth
    auth = OneLogin_Saml2_Auth(req, dict(list(base_configuration.items()) + list(configuration.items())))
  File "/app/env/lib/python3.6/site-packages/onelogin/saml2/auth.py", line 54, in __init__
    self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "/app/env/lib/python3.6/site-packages/onelogin/saml2/settings.py", line 114, in __init__
    ','.join(self.__errors)
onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings: idp_entityId_not_found,idp_sso_not_found
[pid: 46|app: 0|req: 87/302] 10.1.4.0 () {54 vars in 1198 bytes} [Mon Aug 13 13:57:08 2018] GET /saml/sso/okta/
```

[okta-xml.txt](https://github.com/Project-Meerkat/concierge/files/2283208/okta-xml.txt)

**Comment by AadSchippers** [comment]
The **[entityId in okta.xml](https://www.okta.com/exkeovpyd0CbUiH2m0h7/)** leads to a 404, there might be something wrong with the Okta sample app. 
`<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="http://www.okta.com/exkeovpyd0CbUiH2m0h7">`

The other SAML2 SP do indeed work fine.

**Comment by bartjkdp** [comment]
Fixed by re-creating the Okta application.
