### ISSUE TITLE
SAML login throws a server error when configuration is not valid

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#73]
We get a server error when the sysadmin of the connecting organisation made some configuration errors:

```
saml.views.connect,  no emailaddress in samlUserdata found
Internal Server Error: /saml/connect/
Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./saml/views.py", line 284, in connect_and_login
    user = User.objects.get(pk=extid.userid.pk)
AttributeError: 'HttpResponseRedirect' object has no attribute 'userid'
```

Would be nice to provide a user-friendly error instead.

**Comment by AadSchippers** [comment]
Sorted in **[Sorted issue 73: SAML login throws a server error when creating a new account](https://github.com/Project-Meerkat/concierge/commit/f935354fb6e68453514bbafd845f6f12b18c6c23)**
Awaiting customer reply, so suggest to leave this one open for a bit.
