### ISSUE TITLE
Exception while logging in

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#75]
When logging in I got the following exception (error 500):

```
Internal Server Error: /login/login/
Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "./core/class_views.py", line 104, in post
    response = self.post_login(request, *args, **kwargs)
  File "./core/class_views.py", line 112, in post_login
    if form.is_valid():
  File "/app/env/lib/python3.6/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/app/env/lib/python3.6/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/app/env/lib/python3.6/site-packages/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/app/env/lib/python3.6/site-packages/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "./core/forms.py", line 154, in clean
    username = self.cleaned_data.get('username').lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Two-factor is enabled for my account. Not sure what happens.

**Comment by bartjkdp** [comment]
Cannot reproduce anymore... maybe new build?
