### ISSUE TITLE
Exception in /mod/profile/icondirect.php

### ISSUE THREAD

**Issue by bartjkdp** [Project-Meerkat/concierge#77]
Catched the following exception on production:

```
Internal Server Error: /mod/profile/icondirect.php
Traceback (most recent call last):
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./core/views.py", line 177, in avatar
    user = User.objects.get(id=int(request.GET['guid']))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by AadSchippers** [comment]
Sorted in **[sorted issue #77: Exception in /mod/profile/icondirect.php](https://github.com/Project-Meerkat/concierge/commit/3f41b1b16ceebd3f89d146f9039a65d56b61fe17)**
